### ISSUE TITLE
LayerSwitcher and ZoomBox

### ISSUE THREAD

**Issue by nachouve** [IET-Xunta/XVM#10]
When follow this steps: 
- Select ZoomBox
- Extent LayerSwitcher
- Click on a checkbox or radiobutton

Map makes a unwanted zoom.

**Comment by nachouve** [comment]
This happens with other tools also (measurements).

**Comment by michogar** [comment]
Don't happens to me. Works perfectly. Only when chooses measurement controls then appears Handler layer into LayerSwitcher like OpenLayers.Handler... Is this a bug with layer's name or with layerswitcher behaviour?

**Comment by jorgelf** [comment]
Like @michogar, I can't reproduce it, although that problem happens sometimes when you click onto empty areas of the layer switcher, but I think that's completely acceptable as long as it works fine with the controls, and it does in my browser. I'm closing this, and the latter problem I described is a 'Won't fix' for me. If someone else experiences this problem, notify us.
