### ISSUE TITLE
LayerSwitcher enhancements

### ISSUE THREAD

**Issue by nachouve** [IET-Xunta/XVM#16]
-  Can we configure the  "Base Layers" and "Overlays" text on the LayerSwitcher? And remove it?
-  "Base Layers" should appears at the bottom of the list

**Comment by jorgelf** [comment]
Should be no major problem making them customizable through the yaml in our custom Tree one, but the default one doesn't provide any of those functionalities. We'd have to copy and hack it...

**Comment by jorgelf** [comment]
Added support for customization in the custom one, both base layers position and internationalized messages for Overlays and Base Layer. Can't completely remove those folders though, gotta look into this.

**Comment by jorgelf** [comment]
Now you have the option of removing those nodes in the Custom one. If you put a blank internationalized message for their title, they are ignored. Please note an empty string won't work because it's completely ignored by i18n, but a simple whitespace works.

**Comment by otsix** [comment]
Ok, it works perfectly!

Anyway, we can consider it as a workaround, but I'd prefer some kind of option as "groupBaseLayers=false" and "groupOverlayLayers=false" to establish that the behavior and not overwrite translations.

**Comment by jorgelf** [comment]
I agree that the workaround was kinda lame. Will probably add more options for customizing the LayerSwitcher soon, and among them we'll probably have this one.
