### ISSUE TITLE
BaseLayer default

### ISSUE THREAD

**Issue by nachouve** [IET-Xunta/XVM#17]
A Base Layer with  visibility=true on the map.layers.yaml is changed to false on XVM init.

**Comment by jorgelf** [comment]
Right now, the base layer with the biggest position is set as the default one. Visibility is completely ignored for new base layers.
If someone doesn't like this approach, tell us how do you think it'd work. ;-)

**Comment by nachouve** [comment]
I think the "visibility" should have priority over the order of the layer. That is, if I have 4 base layers but only one has visibility = true this one has to be displayed as base. Only all base layers have visibility=false should be apply the rule of the biggest position is the default one. What do you think?

**Comment by jorgelf** [comment]
This is just a matter of preferences, so if you think as a user that it should work that way, I see no problem in changing its behaviour.

**Comment by michogar** [comment]
I am studying this issue. I think what it says is a normal behavior for the
base layers.

2013/1/30 Jorge López Fernández notifications@github.com

> This is just a matter of preferences, so if you think as a user that it
> should work that way, I see no problem in changing its behaviour.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IET-Xunta/XVM/issues/17#issuecomment-12884359.

## 

Micho Garcia
http://geomati.co
