### ISSUE TITLE
ZoomIn control are placed as last element of the control panel

### ISSUE THREAD

**Issue by nachouve** [IET-Xunta/XVM#18]
I remove all "position" tags on individual yaml control files.

Set on "map.controls.yaml" this:

``` javascript
{
  controls: [
    FeatureInfo,
    ZoomIn,
    ZoomOut,
    ZoomBox,
    ZoomToMaxExtent,
    NavigationHistory,
    CustomLayerSwitcher,
    Scale,
    ScaleLine,
    MousePosition,
    Navigation,
    MeasureLine,
    MeasureArea,
    PermalinkButton,
    HelpButton
  ],
  TOC : !!bool false
}
```

ZoomIn control are place on the last position of the control panel.

**Comment by jorgelf** [comment]
Sorry, but for me it works perfectly...
Removed the line
`position: !!int 20`
from _ZoomIn.yaml_, and set the _map.controls.yaml_ to what you posted and controls are shown exactly in that order, ZoomIn being the second. Have you made any local changes to the code (specially _Control.js_, _Controls.js_, _ControlLoader.js_)? You can check the commit with the specific code for this functionality in case you are not sure: 5347237eaba0fe1c7dc1175f90b66d210097fb38

**Comment by michogar** [comment]
For me works perfectly too, close this issue.
