### ISSUE TITLE
EventBus saves listeners repeatedly 

### ISSUE THREAD

**Issue by michogar** [IET-Xunta/XVM#2]
When executes fireEvent eventbus method this repeat operations as many times as listeners has

**Comment by jorgelf** [comment]
I'm not sure I understand this issue. You mean if I store two listeners on one event and execute the fireEvent method on it each of them is called twice? Tested this with a mock and it doesn't happen...

**Comment by michogar** [comment]
A could not reproduce this issue, closes it
