### ISSUE TITLE
Do not use the urlWMS get parameter

### ISSUE THREAD

**Issue by nachouve** [IET-Xunta/XVM#4]
It try that params: 

http://.....? URLWMS=http://ideg.xunta.es/wms_orto_1956-57/request.aspx&LAYERID=Ortofoto_56_57&LAYERTITLE=Ortofoto_56_57&BBOX=616543.03392808,4781543.0339281,655678.79241011,4820678.7924101

But it doesn't work.

**Comment by michogar** [comment]
Runs for me with:

http://localhost/dev/XVM/xvm.html?layertitle=pruebas&layerid=geomatico:estadomasasaugasubterraneas&urlwms=http://192.168.0.249:5080/geoserver/geomatico/wms

and with

http://localhost/dev/XVM/xvm.html?layertitle=pruebas&layerid=geomatico:estadomasasaugasubterraneas&urlwms=http://192.168.0.249:5080/geoserver/geomatico/wms&BBOX=616543.03392808,4781543.0339281,655678.79241011,4820678.7924101

but is not yet implemented BBOX parameter utilization

**Comment by nachouve** [comment]
I can not get this to work:
http://localhost/XVM/xvm.html?layertitle=catastro&layerid=CATASTRO&urlwms=http://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx

On the old XVM, it works:
http://visorgis.cmati.xunta.es/xeovisor/xeoportal.php?urlWMS=http://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx&layerID=CATASTRO&layerTitle=catastro

**Comment by michogar** [comment]
Runs OK, but is not visible. Defaults set visibility as false. You can see if add a layerswitcher. Copy this code in Map.js line 138, after this other line[1]

```
    this.OLMap.addControl(new OpenLayers.Control.LayerSwitcher());
    console.log(this.OLMap);
```

After destroy this code!! ;-)

 [1] https://github.com/michogar/XVM/blob/master/src/Map.js#L137
